<a href="https://colab.research.google.com/github/sakshamorsmthidk/Pytorch-tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

**LISTS**

In [3]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

**NUMPY ARRAYS**

In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.21076259, 0.68756064, 0.62963649, 0.25957201],
       [0.0764731 , 0.1080838 , 0.83369179, 0.26253901],
       [0.17061541, 0.46194188, 0.61451913, 0.49433139]])

**TENSORS**

In [6]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.2051, -0.1702, -1.6547, -1.1731],
        [ 1.3041,  1.7968, -0.6418,  0.7145],
        [-1.4309,  1.5085,  1.2539,  1.8641]])

In [8]:
tensor_3d = torch.randn(2,3,4)
tensor_3d

tensor([[[-0.2298, -0.0520, -0.2024, -0.7181],
         [-0.7944, -0.3044, -1.4471,  0.1221],
         [-0.2159, -0.1808,  0.3987, -0.5099]],

        [[-0.0965, -0.2762, -0.0604, -0.5972],
         [ 2.4026,  0.4888, -2.4863,  0.5950],
         [-2.4051, -0.9267,  0.0721,  0.3836]]])

In [9]:
#Convert numpy to tensor
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.2108, 0.6876, 0.6296, 0.2596],
        [0.0765, 0.1081, 0.8337, 0.2625],
        [0.1706, 0.4619, 0.6145, 0.4943]], dtype=torch.float64)